name: Publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
        profile: minimal
        override: true

    - name: Build
      run: cargo build --release --all-features

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/speculare-client
        asset_name: speculare-client-linux-amd64
        tag: ${{ github.ref }}
        overwrite: true